<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Cause List {{ $causeList->list_date->format('Y-m-d') }}</title>
    <style>
        body { font-family: 'Times New Roman', Georgia, serif; font-size: 11pt; color: #1a1a1a; margin: 30px; }
        .header { text-align: center; border-bottom: 3px double #333; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { font-size: 18pt; margin: 4px 0; letter-spacing: 1px; }
        .header h2 { font-size: 14pt; margin: 4px 0; font-weight: normal; }
        .meta { display: flex; justify-content: space-between; font-size: 10pt; color: #444; margin: 12px 0 20px; }
        table { width: 100%; border-collapse: collapse; font-size: 10pt; }
        th { background: #2a2a2a; color: white; text-align: left; padding: 8px; text-transform: uppercase; letter-spacing: 0.5px; font-size: 9pt; }
        td { padding: 7px 8px; border-bottom: 1px solid #ddd; vertical-align: top; }
        .case-num { font-family: monospace; font-size: 9pt; }
        .track { font-size: 8pt; text-transform: uppercase; padding: 2px 6px; letter-spacing: 0.5px; }
        .track-fast { background: #fef3f2; color: #9d2424; }
        .track-standard { background: #fef9e7; color: #92580d; }
        .track-complex { background: #ecf3f8; color: #1e4d6b; }
        .footer { margin-top: 30px; font-size: 9pt; color: #666; text-align: center; border-top: 1px solid #ccc; padding-top: 12px; }
    </style>
</head>
<body>

<div class="header">
    <h1>{{ strtoupper($causeList->court->name) }}</h1>
    <h2>CAUSE LIST</h2>
    <h2 style="font-size:12pt; font-weight:bold; margin-top:8px;">{{ $causeList->list_date->format('l, d F Y') }}</h2>
</div>

<div class="meta">
    <div>
        <strong>Presiding:</strong> {{ $causeList->judge->user->name }}<br>
        <strong>Courtroom:</strong> {{ $causeList->judge->courtroom_number }}
    </div>
    <div style="text-align:right">
        <strong>Total Cases:</strong> {{ $causeList->total_cases }}<br>
        <strong>Generated:</strong> {{ $causeList->generated_at?->format('d M Y, H:i') }}
    </div>
</div>

<table>
    <thead>
        <tr>
            <th style="width:30px">#</th>
            <th style="width:60px">Time</th>
            <th style="width:110px">Case No.</th>
            <th>Title / Parties</th>
            <th style="width:80px">Stage</th>
            <th style="width:70px">Track</th>
        </tr>
    </thead>
    <tbody>
        @foreach($causeList->items as $item)
        @php $case = $item->case; @endphp
        <tr>
            <td>{{ $item->serial_number }}</td>
            <td>{{ \Carbon\Carbon::parse($item->estimated_time_slot)->format('H:i') }}</td>
            <td class="case-num">{{ $case->case_number }}</td>
            <td>
                <strong>{{ $case->title }}</strong><br>
                <span style="font-size:9pt; color:#555">
                    @php
                        $p = $case->parties->whereIn('party_type', ['petitioner', 'plaintiff', 'complainant'])->first();
                        $r = $case->parties->whereIn('party_type', ['respondent', 'defendant', 'accused'])->first();
                    @endphp
                    {{ $p?->name ?? '—' }} <em>v.</em> {{ $r?->name ?? '—' }}
                </span>
            </td>
            <td style="font-size:9pt; text-transform:capitalize">{{ str_replace('_', ' ', $case->current_stage) }}</td>
            <td><span class="track track-{{ $item->track_at_listing }}">{{ $item->track_at_listing }}</span></td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by DCFM Court Management System · {{ now()->format('d M Y H:i') }}<br>
    Cases ordered by track (fast → standard → complex) and priority score within each track
</div>

</body>
</html>
